version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: moodle_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # MARIADB_CHARACTER_SET: utf8mb4
      # MARIADB_COLLATE: utf8mb4_unicode_ci
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:8080"
    environment:
      MOODLE_DATABASE_TYPE: ${MOODLE_DATABASE_TYPE}
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_NAME: ${MOODLE_DATABASE_NAME}
      MOODLE_DATABASE_USER: ${MOODLE_DATABASE_USER}
      MOODLE_DATABASE_PASSWORD: ${MOODLE_DATABASE_PASSWORD}
    volumes:
      - moodle_data:/bitnami/moodle
      - moodle_php_data:/bitnami/php
      - moodle_apache_conf:/bitnami/apache/conf
    # restart: "no"
    # entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  db_data:
    external: true
  moodle_data:
    external: true
  moodle_php_data:
    external: true
  moodle_apache_conf:
