version: '3.8'
services:
  db:
    #image: mariadb:latest
    image: bitnami/mariadb:latest
    container_name: moodle_db
    environment:
      - MARIADB=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'db_data:/bitnami/mariadb'
    # networks:
    #   - moodle-network

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle_app
    #restart: always
    depends_on:
      - db
    ports:
      - "80:8080"
      # If you want to expose HTTPS from the container, you could also map 443
      - "443:8443"
    environment:
      - MOODLE_DATABASE_TYPE=mariadb
      # - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_NAME=${MARIADB_DATABASE}
      # - MOODLE_DATABASE_USER=${MARIADB_USER}
      # - MOODLE_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      # Optionally set SITE_URL if you have a domain:
      # - MOODLE_SITE_URL=http://example.com
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=${MARIADB_USER}
      - MOODLE_DATABASE_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    # networks:
    #   - moodle-network

volumes:
  db_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
